- name: Create a maintenance window for a Zabbix host
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    zabbix_api_url: "http://172.29.57.115/zabbix/api_jsonrpc.php"
    zabbix_user: "Admin"
    zabbix_password: "zabbix"
    host_name: "{{ Hostname }}"
    maintenance_name: "{{ Maintenance_Name + (ansible_date_time.epoch | int) }}"
    maintenance_description: "{{ Reason_Justification }}"
    maintenance_time_start: "{{ (Active_Since | int) + 60 }}"
    maintenance_duration: "{{ Period }}"

  tasks:
    - name: Get Zabbix auth token
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            username: "{{ zabbix_user }}"
            password: "{{ zabbix_password }}"
          id: 1
        return_content: yes
      register: auth_response

    - name: Debug auth response
      debug:
        var: auth_response

    - name: Set Zabbix auth token
      set_fact:
        zabbix_auth_token: "{{ auth_response.json.result | default('') }}"

    - name: Fail if auth token is not set
      fail:
        msg: "Failed to get Zabbix auth token."
      when: zabbix_auth_token == ''

    - name: Get all hosts
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          jsonrpc: "2.0"
          method: "host.get"
          params:
            output: ["hostid", "name"]
          auth: "{{ zabbix_auth_token }}"
          id: 2
        return_content: yes
      register: all_hosts_response

    - name: Debug all hosts response
      debug:
        var: all_hosts_response

    - name: Filter host by name case-insensitively
      set_fact:
        host_id: "{{ (all_hosts_response.json.result | selectattr('name', 'search', host_name | lower) | list | first).hostid | default('') }}"

    - name: Fail if host ID is not set
      fail:
        msg: "Failed to get host ID."
      when: host_id == ''

    - name: Create maintenance window
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          jsonrpc: "2.0"
          method: "maintenance.create"
          params:
            name: "{{ maintenance_name }}"
            active_since: "{{ maintenance_time_start | int }}"
            active_till: "{{ (maintenance_time_start | int) + (maintenance_duration | int) }}"
            description: "{{ maintenance_description }}"
            hostids:
              - "{{ host_id }}"
            timeperiods:
              - timeperiod_type: 0  # one-time maintenance
                start_date: "{{ maintenance_time_start | int }}"
                period: "{{ maintenance_duration | int }}"
          auth: "{{ zabbix_auth_token }}"
          id: 3
        return_content: yes
      register: maintenance_response

    - name: Output maintenance creation response
      debug:
        var: maintenance_response
