---
- name: Create a maintenance window for a Zabbix host
  hosts: localhost
  vars:
    zabbix_api_url: "http://your_zabbix_server/api_jsonrpc.php"
    zabbix_user: "your_zabbix_user"
    zabbix_password: "your_zabbix_password"
    host_name: "your_host_name"
    maintenance_name: "Maintenance Window"
    maintenance_description: "Scheduled maintenance"
    maintenance_time_start: "{{ (ansible_date_time.epoch | int) + 60 }}"  # Start time, 60 seconds from now
    maintenance_duration: 3600  # Duration in seconds (1 hour)

  tasks:
    - name: Get Zabbix auth token
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            user: "{{ zabbix_user }}"
            password: "{{ zabbix_password }}"
          id: 1
        return_content: yes
      register: auth_response

    - name: Set Zabbix auth token
      set_fact:
        zabbix_auth_token: "{{ auth_response.json.result }}"

    - name: Get host ID by host name
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ zabbix_auth_token }}"
        body:
          jsonrpc: "2.0"
          method: "host.get"
          params:
            output: ["hostid"]
            filter:
              host: ["{{ host_name }}"]
          auth: "{{ zabbix_auth_token }}"
          id: 2
        return_content: yes
      register: host_response

    - name: Set host ID
      set_fact:
        host_id: "{{ host_response.json.result[0].hostid }}"

    - name: Create maintenance window
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ zabbix_auth_token }}"
        body:
          jsonrpc: "2.0"
          method: "maintenance.create"
          params:
            name: "{{ maintenance_name }}"
            active_since: "{{ maintenance_time_start }}"
            active_till: "{{ maintenance_time_start | int + maintenance_duration }}"
            description: "{{ maintenance_description }}"
            hostids:
              - "{{ host_id }}"
            timeperiods:
              - timeperiod_type: 0  # one-time maintenance
                start_date: "{{ maintenance_time_start }}"
                period: "{{ maintenance_duration }}"
          auth: "{{ zabbix_auth_token }}"
          id: 3
        return_content: yes
      register: maintenance_response

    - name: Output maintenance creation response
      debug:
        var: maintenance_response
