# If you want to use Username and Password to be authenticated by Zabbix Server
task:
- name: Set API token
  ansible.builtin.set_fact:
    ansible_zabbix_auth_key: 4f92cee14a57fc618ba782f332a715116b0072bf8e699069fcd0d30853037805

- name: Create a named maintenance window for host www1 for 90 minutes
  # set task level variables as we change ansible_connection plugin here
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "http://172.29.57.115/zabbix"  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
    ansible_host: http://172.29.57.115
  community.zabbix.zabbix_maintenance:
    name: {{Maintenance_name}}
    host_name: {{Hostname}}
    state: present
    minutes: 90
