---
- hosts: all
  gather_facts: false
  tasks:
    - name: Print all variables
      debug:
        var: vars

    - name: Print hostname
      debug:
        msg: "Extra Vars change from test: {{ extra_vars.hostname }}"
