- name: Take VM snapshot
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_name: "{{ vm }}"  # Map `vm` from payload to `vm_name` variable (if needed)
    snapshot_date: "{{ date }}"  # Map `date` from payload to `snapshot_date` variable (if needed)

  tasks:
    - name: Debug VM name
      debug:
        msg: "VM Name is: {{ vm }}"  # Use the `vm` variable directly

    - name: Debug Date
      debug:
        msg: "Snapshot Date is: {{ date }}"  # Use the `date` variable directly
